services:
  postgres:
    image: postgres:latest
    restart: always
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/postgresql/data

volumes:
  postgres_data:
